const db = [
    {
        id: 1,
        username: 'anushkapandey',
        password: '12345',
        phone: '1234567890',
        email: 'anushkap161@gmail.com',
        address: 'Delhi, India',
        age: 26,
        occupation: 'Software Engineer',
        name: 'Anushka Pandey',
        profile_photo: 'https://raw.githubusercontent.com/anushka2911/images/main/uploads/anna-oliinyk-1TSNBEzGIEQ-unsplash.jpg',
        created_at: '2021-08-10 12:00:00',
    },

    {
        id: 2,
        username: 'carl johnson',
        password: 'carljohns67453',
        phone: '9453289343',
        email: 'carljohn@yahoo.com',
        address: 'Punjab, India',
        age: 34,
        occupation: 'Sales Manager',
        name: 'Carl Johnson',
        profile_photo: 'https://raw.githubusercontent.com/anushka2911/images/main/uploads/jason-moyer-A73ah5JKtVA-unsplash.jpg',
        created_at: '2023-18-10 02:40:43',
    },

    {
        id: 3,
        username: 'rahulverma',
        password: 'rahul@2022',
        phone: '9876543210',
        email: 'rahul.verma@email.com',
        address: 'Punjab, India',
        age: 28,
        occupation: 'Data Scientist',
        name: 'Rahul Verma',
        profile_photo: 'https://raw.githubusercontent.com/anushka2911/images/main/uploads/christina-wocintechchat-com-Zpzf7TLj_gA-unsplash.jpg',
        created_at: '2022-05-15 09:30:20',
    },

    {
        id: 4,
        username: 'poonamgupta',
        password: 'gupta@123',
        phone: '88005553535',
        email: 'poonam.gupta@email.com',
        address: 'Punjab, India',
        age: 31,
        occupation: 'Accountant',
        name: 'Poonam Gupta',
        profile_photo: 'https://raw.githubusercontent.com/anushka2911/images/main/uploads/austin-distel-7uoMmzPd2JA-unsplash.jpg',
        created_at: '2021-11-25 15:10:05',
    },

    {
        id: 5,
        username: 'vikramsharma',
        password: 'sharma@vikram',
        phone: '7012345678',
        email: 'vikram.sharma@email.com',
        address: 'Punjab, India',
        age: 29,
        occupation: 'Marketing Specialist',
        name: 'Vikram Sharma',
        profile_photo: 'https://raw.githubusercontent.com/anushka2911/images/main/uploads/jake-nackos-IF9TK5Uy-KI-unsplash.jpg',
        created_at: '2023-02-28 18:45:30',
    },

    {
        id: 6,
        username: 'divyasingh',
        password: 'singh.divya',
        phone: '9898989898',
        email: 'divya.singh@email.com',
        address: 'Punjab, India',
        age: 27,
        occupation: 'UX Designer',
        name: 'Divya Singh',
        profile_photo: 'https://raw.githubusercontent.com/anushka2911/images/main/uploads/podmatch-CgCH4V4cNGk-unsplash.jpg',
        created_at: '2022-09-14 07:20:15',
    },

    {
        id: 7,
        username: 'arjunmehta',
        password: 'mehta@arjun',
        phone: '7777777777',
        email: 'arjun.mehta@email.com',
        address: 'Mumbai, India',
        age: 33,
        occupation: 'Project Manager',
        name: 'Arjun Mehta',
        profile_photo: 'https://raw.githubusercontent.com/anushka2911/images/main/uploads/anna-oliinyk-1TSNBEzGIEQ-unsplash.jpg',
        created_at: '2023-04-03 11:55:40',
    },

    {
        id: 8,
        username: 'nehaagrawal',
        password: 'neha@agrawal',
        phone: '9999999999',
        email: 'neha.agrawal@email.com',
        address: 'Chittorgarh, India',
        age: 30,
        occupation: 'HR Consultant',
        name: 'Neha Agrawal',
        profile_photo: 'https://raw.githubusercontent.com/anushka2911/images/main/uploads/jason-moyer-A73ah5JKtVA-unsplash.jpg',
        created_at: '2022-07-20 14:30:25',
    },

    {
        id: 9,
        username: 'sandeepverma',
        password: 'verma@sandeep',
        phone: '7778889999',
        email: 'sandeep.verma@email.com',
        address: 'Punjab, India',
        age: 32,
        occupation: 'Software Developer',
        name: 'Sandeep Verma',
        profile_photo: 'https://raw.githubusercontent.com/anushka2911/images/main/uploads/christina-wocintechchat-com-Zpzf7TLj_gA-unsplash.jpg',
        created_at: '2021-12-05 08:15:10',
    },

    {
        id: 10,
        username: 'ananyasingh',
        password: 'singh@ananya',
        phone: '8888888888',
        email: 'ananya.singh@email.com',
        address: 'Mohali, India',
        age: 28,
        occupation: 'Marketing Analyst',
        name: 'Ananya Singh',
        profile_photo: 'https://raw.githubusercontent.com/anushka2911/images/main/uploads/austin-distel-7uoMmzPd2JA-unsplash.jpg',
        created_at: '2023-01-30 16:40:55',
    },

    {
        id: 11,
        username: 'rohitpatel',
        password: 'rohit@patel',
        phone: '7777778888',
        email: 'rohit.patel@email.com',
        address: 'Punjab, India',
        age: 31,
        occupation: 'Financial Analyst',
        name: 'Rohit Patel',
        profile_photo: 'https://raw.githubusercontent.com/anushka2911/images/main/uploads/jake-nackos-IF9TK5Uy-KI-unsplash.jpg',
        created_at: '2022-06-18 10:25:30',
    },

    {
        id: 12,
        username: 'komaljha',
        password: 'jha@komal',
        phone: '9876543211',
        email: 'komal.jha@email.com',
        address: 'Amritsar, India ',
        age: 26,
        occupation: 'UX/UI Designer',
        name: 'Komal Jha',
        profile_photo: 'https://raw.githubusercontent.com/anushka2911/images/main/uploads/podmatch-CgCH4V4cNGk-unsplash.jpg',
        created_at: '2023-03-12 13:50:15',
    },

    {
        id: 13,
        username: 'rahulkumar',
        password: 'kumar@rahul',
        phone: '9898989899',
        email: 'rahul.kumar@email.com',
        address: 'Punjab, India',
        age: 29,
        occupation: 'Software Engineer',
        name: 'Rahul Kumar',
        profile_photo: 'https://raw.githubusercontent.com/anushka2911/images/main/uploads/anna-oliinyk-1TSNBEzGIEQ-unsplash.jpg',
        created_at: '2021-09-28 17:15:40',
    },

    {
        id: 14,
        username: 'priyankasharma',
        password: 'sharma@priyanka',
        phone: '9998887777',
        email: 'priyanka.sharma@email.com',
        address: 'Punjab, India',
        age: 33,
        occupation: 'Digital Marketing Specialist',
        name: 'Priyanka Sharma',
        profile_photo: 'https://raw.githubusercontent.com/anushka2911/images/main/uploads/jason-moyer-A73ah5JKtVA-unsplash.jpg',
        created_at: '2022-04-05 12:40:25',
    },

    {
        id: 15,
        username: 'arjunsingh',
        password: 'singh@arjun',
        phone: '7777777778',
        email: 'arjun.singh@email.com',
        address: 'Punjab, India',
        age: 30,
        occupation: 'Project Manager',
        name: 'Arjun Singh',
        profile_photo: 'https://raw.githubusercontent.com/anushka2911/images/main/uploads/austin-distel-7uoMmzPd2JA-unsplash.jpg',
        created_at: '2023-08-20 15:15:10',
    },

    {
        id: 16,
        username: 'radhikagupta',
        password: 'gupta@radhika',
        phone: '8888888889',
        email: 'radhika.gupta@email.com',
        address: 'Pune, India',
        age: 28,
        occupation: 'UX Designer',
        name: 'Radhika Gupta',
        profile_photo: 'https://raw.githubusercontent.com/anushka2911/images/main/uploads/jake-nackos-IF9TK5Uy-KI-unsplash.jpg',
        created_at: '2022-11-10 09:40:55',
    },

    {
        id: 17,
        username: 'abhishekkumar',
        password: 'kumar@abhishek',
        phone: '7777779999',
        email: 'abhishek.kumar@email.com',
        address: 'Mumbai, India',
        age: 32,
        occupation: 'Software Developer',
        name: 'Abhishek Kumar',
        profile_photo: 'https://raw.githubusercontent.com/anushka2911/images/main/uploads/christina-wocintechchat-com-Zpzf7TLj_gA-unsplash.jpg',
        created_at: '2023-06-25 14:25:30',
    },

    {
        id: 18,
        username: 'ritikaverma',
        password: 'verma@ritika',
        phone: '9999999990',
        email: 'ritika.verma@email.com',
        address: 'Puttaparthi, India',
        age: 29,
        occupation: 'Financial Analyst',
        name: 'Ritika Verma',
        profile_photo: 'https://raw.githubusercontent.com/anushka2911/images/main/uploads/anna-oliinyk-1TSNBEzGIEQ-unsplash.jpg',
        created_at: '2022-01-15 18:50:15',
    },

    {
        id: 19,
        username: 'viveksharma',
        password: 'sharma@vivek',
        phone: '9876543212',
        email: 'vivek.sharma@email.com',
        address: 'Kolkata, India',
        age: 31,
        occupation: 'Marketing Specialist',
        name: 'Vivek Sharma',
        profile_photo: 'https://raw.githubusercontent.com/anushka2911/images/main/uploads/podmatch-CgCH4V4cNGk-unsplash.jpg',
        created_at: '2023-04-30 11:15:40',
    },

    {
        id: 20,
        username: 'soniyasingh',
        password: 'singh@soniya',
        phone: '7777777788',
        email: 'soniya.singh@email.com',
        address: 'New Delhi, India',
        age: 27,
        occupation: 'Graphic Designer',
        name: 'Soniya Singh',
        profile_photo: 'https://raw.githubusercontent.com/anushka2911/images/main/uploads/jake-nackos-IF9TK5Uy-KI-unsplash.jpg',
        created_at: '2022-10-05 10:40:25',
    },
];

export default db;
